M48
; DRILL file KiCad 10.0.2 date 2026-07-15T20:47:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-15T20:47:36+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X161.815Y-122.845
X167.595Y-122.845
X174.685Y-122.87
X180.465Y-122.87
M30
