M48
; DRILL file KiCad 10.0.2 date 2026-07-10T11:54:40
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-10T11:54:40+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X161.81Y-122.495
X167.59Y-122.495
X174.68Y-122.52
X180.46Y-122.52
M30
